name: Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: self-hosted

    env:
      REGISTRY: 10.246.127.193:5000
      IMAGE_NAME: cicd-lab

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t $IMAGE_NAME:test .

      - name: Run tests
        run: docker run --rm $IMAGE_NAME:test npm test

      - name: Login to private registry
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" --username "$REGISTRY_USERNAME" --password-stdin

      - name: Tag image
        run: |
          docker tag $IMAGE_NAME:test $REGISTRY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:test $REGISTRY/$IMAGE_NAME:$GITHUB_SHA

      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA

      - name: Cleanup
        if: always()
        run: |
          docker image rm $IMAGE_NAME:test || true
